name: Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: mkdir build
      - name: cmake
        run: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_NUMBER=${{ github.run_number }} ../
        working-directory: build
      - name: build
        run: cmake --build .
        working-directory: build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/Task*

