name: Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: mkdir build
      - name: cmake
        run: cmake -DCMAKE_BUILD_TYPE=Release ../
        working-directory: build
      - name: build
        run: cmake --build .
        working-directory: build
      - run: echo "Build number is ${github.run_number}"
      - run: echo "Build number is ${github.run_attempt}"

