name: Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir build
      - name: cmake
        run: cmake -DCMAKE_BUILD_TYPE=Release ../
        working-directory: build
      - name: build
        run: cmake --build .
        working-directory: build
